name: Build PROD - Frontend

on:
  pull_request:
    branches:
      - "main"
      - "release"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: test
        uses: ./.github/actions/test
